### ISSUE TITLE
Adding another server to replication group via xDFS

### ISSUE THREAD

**Issue by stephensmalls** [dsccommunity/DFSDsc#36]
I would like to use xdfs to add a new server to an already existing replication group. All of the examples seem to build one. Her's my code, but it doesn't work. What am I missing?

'xDFSReplicationGroup storage
        {
            GroupName = 'storage'
            Ensure = 'Present'
            Members = 'server1.domain.com','server2.domain.com','server3.domain.com'
            Folders = 'storage'
            PSDSCRunAsCredential = $Credential
            DependsOn = '[WindowsFeature]RSATDFSMgmt'
        }

        xDFSReplicationGroupConnection storage1
        {
            GroupName = 'storage'
            Ensure = 'Present'
            SourceComputerName = 'server1.domain.com'
            DestinationComputerName = 'server3.domain.com'
            PSDSCRunAsCredential = $Credential
        }

        xDFSReplicationGroupConnection storage2
        {
            GroupName = 'storage'
            Ensure = 'Present'
            SourceComputerName = 'server2.domain.com'
            DestinationComputerName = 'server3.domain.com'
            PSDSCRunAsCredential = $Credential
        }

        xDFSReplicationGroupFolder storagefolder
        {
            GroupName = 'storage'
            FolderName = 'storage'
            PSDSCRunAsCredential = $Credential
            DependsOn = '[xDFSReplicationGroup]storage'
        }

        xDFSReplicationGroupMembership server3
        {
            GroupName = 'storage'
            FolderName = 'storage'
            ComputerName = 'server3.domain.com'
            ContentPath = 'd:\storage'
            PSDSCRunAsCredential = $Credential
            DependsOn = '[xDFSReplicationGroupFolder]storageFolder'
        }`

**Comment by PlagueHO** [comment]
Hi @stephensmalls 

Off the top of my head, that should work. So, you're adding a third node to a two node group - and implementing a full mesh? That looks like it should work.

Do you get an error or does the additional node not get joined to the replication group? Are you able to output any verbose logs that are produced when applying the DSC Configuration?

What I would recommend though is that you actually use DSC to configure the entire DFS replication group rather than just part of it. Because in theory, if the first two nodes are configured, this shouldn't cause any change to the replication of the existing nodes, but it will configure the full mesh replication group. It is designed to be idempotent if the DFS replication group is already in state.
